apiVersion: v2
name: ingress-nginx
description: Nginx Ingress Controller

type: application


version: 0.1.0

appVersion: 1.16.0

dependencies:
  - name: ingress-nginx
    version: 4.4.0
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress-nginx.enabled