apiVersion: v2
name: cert-manager
description: Cert Manager

type: application


version: 0.1.0

appVersion: 1.16.0

dependencies:
  - name: cert-manager
    version: v1.10.1
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled